# Generated by Django 4.1.7 on 2024-08-24 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='ssn',
            field=models.CharField(max_length=11, verbose_name='Social Security Number'),
        ),
    ]
