# Generated by Django 4.1.7 on 2024-08-24 05:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_alter_member_ssn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='ssn',
            field=models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(message="SSN must be in the format '000-00-0000'.", regex='^\\d{3}-\\d{2}-\\d{4}$')], verbose_name='SS #'),
        ),
    ]
